# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1(2c780a18-ca02-4f44-8e4c-153057104a63)'
        azureContainerRegistry: '{"loginServer":"containerizedsiteacr.azurecr.io", "id" : "/subscriptions/2c780a18-ca02-4f44-8e4c-153057104a63/resourceGroups/containerized-site-rg/providers/Microsoft.ContainerRegistry/registries/containerizedsiteacr"}'
        dockerComposeFile: '**/docker-compose-wordpress.yml'
        action: 'Push services'
