apiVersion : apps/v1
kind: Deployment
metadata:
  name: "wordpresskub-ae71"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "wordpresskub-ae71"
  template:
    metadata:
      labels:
        app: "wordpresskub-ae71"
    spec:
      containers:
        - name: "wordpresskub-ae71"
          image: "containerizedsiteacr.azurecr.io/wordpresskub"
          ports:
          - containerPort: 80